name: Auto Version Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Get the Latest Commit Message
        id: get_message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create and Push a New Tag
        env:
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git tag -a $TAG_NAME -m "$COMMIT_MESSAGE"
          git push origin $TAG_NAME
